[package]
name = "server-pilot"
version = "0.1.0"
description = "A server management tool"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
portable-pty = "0.8" # <-- ADDED for terminal support
log4rs = "1.4.0"
log = "0.4.29"
tauri-plugin-shell = "2"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
keyring = { version = "4.1.6", features = ["apple-native-keyring-store"] }
tauri-plugin-notification = "2.3.3"
lazy_static = "1.4"
dirs = "6.0.0"
whoami = "2.1.2"
hostname = "0.4.2"
syntect = { version = "5", default-features = false, features = ["default-fancy"] }
russh = "0.44"
russh-sftp = "2.4"
async-trait = "0.1"
sysinfo = "0.30"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
